# Generated by Django 4.2.6 on 2023-10-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('nature', models.CharField(choices=[('Entrada', 'Entrada'), ('Saída', 'Saída')], max_length=10)),
                ('sinal', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1)),
            ],
        ),
    ]
