# Generated by Django 4.2.6 on 2023-10-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactiontype',
            old_name='sinal',
            new_name='signal',
        ),
    ]
