# Generated by Django 4.2.6 on 2023-10-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge_api', '0002_rename_sinal_transactiontype_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('product_description', models.CharField(max_length=30)),
                ('amount_in_cents', models.IntegerField()),
                ('seller_name', models.CharField(max_length=20)),
                ('transaction_type_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenge_api.transactiontype')),
            ],
        ),
    ]
